//m.hancock - 07/09/2014 10:48:55 AM - Categories master list
var categories = [
"Books and DVDs",
"Books and DVDs > Cookbooks",
"Books and DVDs > Dog Training",
"Books and DVDs > Shooting",
"Camping",
"Camping > Bags and Luggage",
"Camping > Cookware",
"Camping > Flashlights",
"Camping > Knives",
"Clearance",
"Clothing",
"Clothing > Gloves",
"Clothing > Men’s Casual",
"Clothing > Men’s Casual > Hoodies",
"Clothing > Men’s Casual > Shirts",
"Clothing > Men’s Casual > T-Shirts ",
"Clothing > Men’s Hunting Apparel",
"Clothing > Men’s Hunting Apparel > Blaze Orange",
"Clothing > Men’s Hunting Apparel > Camo",
"Clothing > Men’s Hunting Apparel > Upland",
"Clothing > Men’s Hunting Apparel > Upland > Brush Pants and Chaps",
"Clothing > Men’s Hunting Apparel > Upland > Gaiters and Snake Protection",
"Clothing > Men’s Hunting Apparel > Upland > Vests and Game Bags",
"Clothing > Men’s Hunting Apparel > Waterfowl",
"Clothing > Men’s Shooting Apparel",
"Clothing > Men’s Shooting Apparel > Jackets and Coats",
"Clothing > Men’s Shooting Apparel > Shooting Shirts",
"Clothing > Men’s Shooting Apparel > Vests and Shell Pouches",
"Clothing > Women’s Casual",
"Clothing > Women’s Casual > Hoodies",
"Clothing > Women’s Casual > Shirts",
"Clothing > Women’s Casual > T-Shirts ",
"Clothing > Women’s Hunting Apparel",
"Clothing > Women’s Hunting Apparel > Blaze Orange",
"Clothing > Women’s Hunting Apparel > Camo",
"Clothing > Women’s Hunting Apparel > Pink",
"Clothing > Women’s Hunting Apparel > Upland",
"Clothing > Women’s Hunting Apparel > Upland > Brush Pants and Chaps",
"Clothing > Women’s Hunting Apparel > Upland > Gaiters and Snake Protection",
"Clothing > Women’s Hunting Apparel > Upland > Vests and Game Bags",
"Clothing > Women’s Hunting Apparel > Waterfowl",
"Clothing > Women’s Shooting Apparel",
"Clothing > Women’s Shooting Apparel > Conceal Carry Purses and Bags",
"Clothing > Women’s Shooting Apparel > Jackets and Coats",
"Clothing > Women’s Shooting Apparel > Shooting Shirts",
"Clothing > Women’s Shooting Apparel > Vests and Shell Pouches",
"Dog Training and Supplies",
"Dog Training and Supplies > Collars and Harnesses",
"Dog Training and Supplies > Collars and Harnesses > Bells",
"Dog Training and Supplies > Collars and Harnesses > Braided Collars",
"Dog Training and Supplies > Collars and Harnesses > Harnesses",
"Dog Training and Supplies > Collars and Harnesses > Leather collars",
"Dog Training and Supplies > Collars and Harnesses > Reflective collars",
"Dog Training and Supplies > Crates and Carriers",
"Dog Training and Supplies > Crates and Carriers > Crate and Kennel Covers",
"Dog Training and Supplies > Crates and Carriers > Crate Cushions",
"Dog Training and Supplies > Dog Beds",
"Dog Training and Supplies > Dog Training",
"Dog Training and Supplies > Dog Training > Accessories",
"Dog Training and Supplies > Dog Training > Bird Training Accessories",
"Dog Training and Supplies > Dog Training > Books and DVDs",
"Dog Training and Supplies > Dog Training > Bumpers and Dummies",
"Dog Training and Supplies > Dog Training > Launchers",
"Dog Training and Supplies > Dog Training > Scents",
"Dog Training and Supplies > Dog Training > Whistles",
"Dog Training and Supplies > Dog Treats and Toys",
"Dog Training and Supplies > Dog Vests, Boots and Apparel",
"Dog Training and Supplies > E-Collars",
"Dog Training and Supplies > E-Collars > Bark Collars",
"Dog Training and Supplies > E-Collars > Beeper Collars",
"Dog Training and Supplies > E-Collars > Dog Tracking Systems",
"Dog Training and Supplies > E-Collars > E-Collars",
"Dog Training and Supplies > First Aid",
"Dog Training and Supplies > Grooming",
"Dog Training and Supplies > Leashes and Check Cords",
"Dog Training and Supplies > Trainer Apparel",
"Dog Training and Supplies > Trainer Apparel > Handler Vests",
"Dog Training and Supplies > Trainer Apparel > Trainer Accessories",
"Footwear",
"Footwear > Kid’s",
"Footwear > Kid’s > Casual",
"Footwear > Kid’s > Cold Weather",
"Footwear > Kid’s > Hiking",
"Footwear > Kid’s > Hunting",
"Footwear > Kid’s > Rubber",
"Footwear > Kid’s > Snake Protection",
"Footwear > Men’s",
"Footwear > Men’s > Casual",
"Footwear > Men’s > Cold Weather",
"Footwear > Men’s > Hiking",
"Footwear > Men’s > Hunting",
"Footwear > Men’s > Rubber",
"Footwear > Men’s > Snake Protection",
"Footwear > Men’s > Waders",
"Footwear > Women’s",
"Footwear > Women’s > Casual",
"Footwear > Women’s > Cold Weather",
"Footwear > Women’s > Hiking",
"Footwear > Women’s > Hunting",
"Footwear > Women’s > Rubber",
"Footwear > Women’s > Snake Protection",
"Gift Shop",
"Gift Shop > Gift Cards",
"Home and Cabin",
"Home and Cabin > Artwork",
"Home and Cabin > Cookware",
"Home and Cabin > Food",
"Home and Cabin > Food Processing",
"Hunting",
"Hunting > Archery",
"Hunting > Archery > Accessories",
"Hunting > Archery > Arrow Rests",
"Hunting > Archery > Arrows, Shafts and Fletching",
"Hunting > Archery > Bow Tuning",
"Hunting > Archery > Broadheads and Points",
"Hunting > Archery > Cases",
"Hunting > Archery > Releases",
"Hunting > Archery > Sights",
"Hunting > Archery > Targets",
"Hunting > Big Game",
"Hunting > Big Game > Calls",
"Hunting > Big Game > Decoys",
"Hunting > Big Game > Shotgun and Rifle Holsters",
"Hunting > Decoys",
"Hunting > Decoys > Accessories",
"Hunting > Decoys > Big Game",
"Hunting > Decoys > Decoy Bags",
"Hunting > Decoys > Dove",
"Hunting > Decoys > Duck ",
"Hunting > Decoys > Goose",
"Hunting > Decoys > Predator",
"Hunting > Decoys > Turkey",
"Hunting > Game Cameras",
"Hunting > Predator",
"Hunting > Predator > Calls",
"Hunting > Predator > Decoys",
"Hunting > Scents and Scent Eliminators",
"Hunting > Scents and Scent Eliminators > Attractants and Calming Scents",
"Hunting > Scents and Scent Eliminators > Scent Control",
"Hunting > Turkey",
"Hunting > Turkey > Calls",
"Hunting > Turkey > Decoys",
"Hunting > Upland",
"Hunting > Upland > Accessories",
"Hunting > Upland > Brush Pants and Chaps",
"Hunting > Upland > Gaiters and Snake Protection",
"Hunting > Upland > Hats",
"Hunting > Upland > Shotgun Holsters",
"Hunting > Upland > Upland Boots",
"Hunting > Upland > Vests and Game Bags",
"Hunting > Waterfowl",
"Hunting > Waterfowl > Blinds",
"Hunting > Waterfowl > Calls",
"Hunting > Waterfowl > Decoys",
"Shooting",
"Shooting > Books and DVDs",
"Shooting > Choke Tubes",
"Shooting > Eye/Hearing Protection",
"Shooting > Eye/Hearing Protection > Accessories",
"Shooting > Eye/Hearing Protection > Ear Muffs",
"Shooting > Eye/Hearing Protection > Ear Plugs",
"Shooting > Eye/Hearing Protection > Hearing Enhancement",
"Shooting > Eye/Hearing Protection > Shooting Glasses",
"Shooting > Gun Maintenance",
"Shooting > Gun Maintenance > Cleaning Kits",
"Shooting > Gun Maintenance > Gun Care",
"Shooting > Gun Maintenance > Solvents and Lubricants",
"Shooting > Gun Storage",
"Shooting > Gun Storage > Accessories",
"Shooting > Gun Storage > Gun Racks",
"Shooting > Gun Storage > Handgun Safes",
"Shooting > Gun Storage > Hard-Sided Gun Cases",
"Shooting > Gun Storage > Shotgun Safes",
"Shooting > Gun Storage > Soft-Sided Gun Cases",
"Shooting > Holsters",
"Shooting > Holsters > Belts",
"Shooting > Holsters > Conceal  Carry",
"Shooting > Holsters > Hand Gun Holsters",
"Shooting > Holsters > Hull  Bags",
"Shooting > Holsters > Shell Pouches",
"Shooting > Holsters > Shotgun Holsters",
"Shooting > Optics",
"Shooting > Optics > Binoculars",
"Shooting > Optics > Range Finders",
"Shooting > Optics > Scopes",
"Shooting > Optics > Sights",
"Shooting > Reloading",
"Shooting > Reloading > Reloaders",
"Shooting > Reloading > Supplies and Components",
"Shooting > Reloading > Tools and Accessories",
"Shooting > Shooting Accessories",
"Shooting > Shooting Accessories > Conceal Carry Purses and Bags",
"Shooting > Shooting Accessories > Gloves",
"Shooting > Shooting Accessories > Gun Rests",
"Shooting > Shooting Accessories > Hearing Protection",
"Shooting > Shooting Accessories > Range Bags",
"Shooting > Shooting Accessories > Recoil Reducers and Pads",
"Shooting > Shooting Accessories > Shell Pouches and Bags",
"Shooting > Shooting Accessories > Shooting Glasses",
"Shooting > Shooting Accessories > Shooting Sticks",
"Shooting > Shooting Accessories > Stock and Comb Adjustment",
"Shooting > Shooting Accessories > Targets",
"Shooting > Shooting Apparel",
"Shooting > Shooting Apparel > Chaps and Pants",
"Shooting > Shooting Apparel > Conceal Carry Purses and Bags",
"Shooting > Shooting Apparel > Gloves",
"Shooting > Shooting Apparel > Hats",
"Shooting > Shooting Apparel > Hoodies",
"Shooting > Shooting Apparel > Jackets and Coats",
"Shooting > Shooting Apparel > Shirts",
"Shooting > Shooting Apparel > Vests",
"Shooting > Shooting Carts",
"Shooting > Shooting Carts > Shooting Cart Accessories",
"Shooting > Shooting Carts > Shooting Carts",
];